"\"Take him to \\ Detroit!\""
" \\ "
"Y el ingeniero escribio \"Hola mundo\" en codigo C."
"Esto me estresa\"
\"\"
"Y asi se reconoce un buen string"
"I have come here to chew bubble-gum and try this unknown \e escape sequence"
"Good, bad, I'm the one writing the tests \"
"" \"
"Hail to the king, baby.
